[project]
name = "irranalyze"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "gmpy2>=2.3.0",
    "mpmath>=1.3.0",
    "sympy>=1.14.0",
]
